import os
import uuid
from datetime import datetime
from functools import wraps
from pathlib import Path
from email.message import EmailMessage
import smtplib

from sqlalchemy import text
from dotenv import load_dotenv
from flask import (
    Flask,
    flash,
    redirect,
    render_template,
    request,
    send_from_directory,
    url_for,
)
from flask_login import LoginManager, UserMixin, current_user, login_required, login_user, logout_user
from flask_sqlalchemy import SQLAlchemy
from flask_wtf import FlaskForm
from werkzeug.security import check_password_hash, generate_password_hash
from werkzeug.utils import secure_filename
from wtforms import DateField, PasswordField, SelectField, StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo, Length
from pypdf import PdfReader, PdfWriter
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')
UPLOAD_FOLDER = Path(os.environ.get('UPLOAD_FOLDER', BASE_DIR / 'uploads'))
DATABASE_PATH = Path(os.environ.get('DATABASE_PATH', BASE_DIR / 'data' / 'app.db'))

app = Flask(__name__)
app.config.update(
    SECRET_KEY=os.environ.get('SECRET_KEY', 'dev-secret-key'),
    SQLALCHEMY_DATABASE_URI=os.environ.get('DATABASE_URL', f'sqlite:///{DATABASE_PATH}'),
    SQLALCHEMY_TRACK_MODIFICATIONS=False,
    UPLOAD_FOLDER=str(UPLOAD_FOLDER),
    MAIL_SERVER=os.environ.get('MAIL_SERVER', ''),
    MAIL_PORT=int(os.environ.get('MAIL_PORT', 25)),
    MAIL_USE_TLS=os.environ.get('MAIL_USE_TLS', 'false').lower() == 'true',
    MAIL_USE_SSL=os.environ.get('MAIL_USE_SSL', 'false').lower() == 'true',
    MAIL_USERNAME=os.environ.get('MAIL_USERNAME'),
    MAIL_PASSWORD=os.environ.get('MAIL_PASSWORD'),
    MAIL_DEFAULT_SENDER=os.environ.get('MAIL_DEFAULT_SENDER', 'noreply@example.com'),
)

db = SQLAlchemy(app)
login_manager = LoginManager(app)
login_manager.login_view = 'login'

ALLOWED_EXTENSIONS = {'pdf'}
ALLOWED_IMAGE_EXTENSIONS = {'png', 'jpg', 'jpeg'}
CASE_TYPES = [
    ('fournitures_informatiques', 'Fournitures informatiques'),
    ('fournitures_telephoniques', 'Fournitures téléphoniques'),
    ('logiciel', 'Logiciel'),
    ('location_informatique', 'Location informatique'),
    ('maintenance', 'Maintenance'),
    ('entrep_materiel', 'Ent rép matériel'),
    ('liaisons_informatiques', 'Liaisons informatiques'),
    ('telephonie', 'Téléphonie'),
    ('abonnements', 'Abonnements'),
    ('prestations', 'Prestations'),
]

ACCOUNT_NUMBER_CHOICES = [
    ('', 'Sélectionnez un N° de compte'),
    ('Budget Exploitation CHICAS', [
        ('H606253', 'H606253 Achats non stockés fournitures informatiques'),
        ('H606254', 'H606254 Achats non stockés fournitures téléphoniques'),
        ('H612221', 'H612221 Crédit bail informatique : logiciels'),
        ('H613251', 'H613251 Location inform à caractère non médical'),
        ('H6151610', 'H6151610 Maintenance progiciels à caractère médical'),
        ('H6151611', 'H6151611 Maintenance matériels à caractère médical'),
        ('H615254', 'H615254 Ent rép matériel inform caract non médical'),
        ('H6152610', 'H6152610 Maintenance progiciels à caractère non médical'),
        ('H6152611', 'H6152611 Maintenance matériels  à caractère non médical'),
        ('H6152612', 'H6152612 Maintenance logiciels/ bureautiques/SGBD à caractère non médical'),
        ('H6152682', 'H6152682 Maintenance infrastructure téléphonie'),
        ('H6152683', 'H6152683 Maintenance infrastructure TV'),
        ('H6261', 'H6261 Liaisons informatiques ou spécialisées'),
        ('H6265', 'H6265 Téléphonie'),
        ('H62841', 'H62841 Cotisations, abonnements et hébergements informatiques'),
        ('H62842', 'H62842 Prestations informatiques, AMO'),
        ('H65883', 'H65883 Autres charges de gestion courante - SI'),
        ('H6711010', 'H6711010 Intérêts moratoires et pénalités sur marché - SI'),
        ('H672808', 'H672808 Charges sur exercices antérieurs'),
    ]),
    ('Budget exploitation CFPS Gap', [
        ('C61351', 'C61351 Locations informatiques'),
        ('C61554', 'C61554 Ent rep matériel informatique'),
        ('C615261', 'C615261 Maintenance informatique'),
        ('C615618', 'C615618 Maintenance informatique - autres'),
        ('C6261', 'C6261 Liaisons informatiques ou spécialisées'),
        ('C6284', 'C6284 Prestations informatiques'),
    ]),
    ('BUDGET EXPLOITATION - GHT', [
        ('G6151610', 'G6151610 Maintenance progiciels à caractère médical'),
        ('G615254', 'G615254 Maintenance matériel non médical'),
        ('G6152610', 'G6152610 Maintenance progiciels à caractère non médical'),
        ('G6261', 'G6261 Liaisons informatiques ou spécialisées'),
        ('G6265', 'G6265 Telephonie GHT'),
        ('G6284', 'G6284 Prestations informatiques'),
        ('G62841', 'G62841 Prestations'),
        ('G62842', 'G62842 Abonnements'),
        ('G628871', 'G628871 Prestations AUDIT - SI'),
    ]),
    ('BUDGET INVESTISSEMENT', [
        ('H2051205', 'H2051205 Progiciels dissociés - CFPS - SI'),
        ('H2051206', 'H2051206 Progiciels dissociés / PPSI'),
        ('H2051207', 'H2051207 Progiciels dissociés - Plan Directeur'),
        ('H2052000', 'H2052000 Progiciels GHT'),
        ('H21832106', 'H21832106 Matériel informatique - Ets principal/PPSI'),
        ('H21832107', 'H21832107 Matériel informatique - Ets principal - Plan Directeur'),
        ('H218325', 'H218325 Matériel informatique - CFPS'),
        ('H21832600', 'H21832600 Matériel informatique - GHT'),
        ('H237251206', 'H237251206 Acptes / cdes progiciels/PPSI/immob en cours'),
        ('H237251207', 'H237251207 Acptes / cdes progiciels/Plan directeur/immob en cours'),
        ('H238102', 'H238102 Avances versées sur commandes immob corpor. (SI)'),
        ('H2381351807', 'H2381351807 Avances versées sur commandes immob corporelles - autres IGAAC (SI)'),
        ('H2382351807', 'H2382351807 Acomptes versés sur commandes immob corporelles - autres IGAAC (SI)'),
        ('H2382802', 'H2382802 Acomptes versés sur commandes d\'immob. corporelles - autres (SI)'),
    ]),
]

PROJECT_CODE_CHOICES = [
    ('', 'Sélectionnez un code projet'),
    ('2023-SB-ANVR-H-PREVUS_GAP', '2023-SB-ANVR-H-PREVUS_GAP - SB ACHATS NOUVEAUX VETUSTE RENOUVELLEMENT PREVUS'),
    ('2024-LABO-TERRITORIAL_GAP', '2024-LABO-TERRITORIAL_GAP - TOUS GESTIONNAIRES LABORATOIRE TERRITORIAL'),
    ('AAP_ SOINS_SOIGNANTS_GAP', 'AAP_ SOINS_SOIGNANTS_GAP - AAP prendre soin de ceux qui soignent'),
    ('CASSE_GAP', 'CASSE_GAP - CASSE DM'),
    ('MISSION-RESP-POPULATIONNELLE_GAP', 'MISSION-RESP-POPULATIONNELLE_GAP - CHARGE DE MISSION RESPONSABILITE POPULATIONNELLE'),
    ('PRIME_POLE_CHIRANESTREA_CHICAS_GAP', 'PRIME_POLE_CHIRANESTREA_CHICAS_GAP - PRIME DE POLE CHIRURGIE ANESTHESIE REA CHICAS'),
    ('PRIME_POLE_FE_CHICAS_GAP', 'PRIME_POLE_FE_CHICAS_GAP - PRIME DE POLE FEMME ENFANT CHICAS'),
    ('PRIME_POLE_GERONTO_CHICAS_GAP', 'PRIME_POLE_GERONTO_CHICAS_GAP - PRIME DE POLE GERONTOLOGIE CHICAS'),
    ('PRIME_POLE_MEDICAL_CHICAS_GAP', 'PRIME_POLE_MEDICAL_CHICAS_GAP - PRIME DE POLE MEDICAL CHICAS'),
    ('PRIME_POLE_MT_CHICAS_GAP', 'PRIME_POLE_MT_CHICAS_GAP - PRIME DE POLE MEDICO TECH CHICAS'),
    ('PRIME_POLE_SC_CHICAS_GAP', 'PRIME_POLE_SC_CHICAS_GAP - PRIME DE POLE SOINS CRITIQUES CHICAS'),
    ('SI-CURSUS-HEMO_GAP', 'SI-CURSUS-HEMO_GAP - LOGICIEL HEMOVIGILANCE'),
    ('SI-CYBERSECURITE_GAP', 'SI-CYBERSECURITE_GAP - SI sécurité du SI / Cybersécurité'),
    ('SI-HMFORMS_GAP', 'SI-HMFORMS_GAP - SI logiciel HM FORMS'),
    ('SI-INFRATECH-RESEAU_GAP', 'SI-INFRATECH-RESEAU_GAP - SI infrastructure technique /reseau'),
    ('SI-LOGDIVERS_GAP', 'SI-LOGDIVERS_GAP - SI PROGICIELS DIVERS'),
    ('SI-PARCINFO_GAP', 'SI-PARCINFO_GAP - SI parc info + TV'),
    ('SI-SSO_GAP', 'SI-SSO_GAP - SSO-SYSTANCIA GHT'),
    ('VACC_HPV_GAP', 'VACC_HPV_GAP - Campagne de Vaccination HPV'),
    ('2021 SE ASS ANVR H', '2021 SE ASS ANVR H - SE ASS ACHATS NOUVEAUX VETUSTE RENOUVELLEMENT'),
    ('2021 SI QUAL GDR', '2021 SI QUAL GDR - SI QUALITE ET GESTION DES RISQUES'),
    ('2021 SI QUAL LABO', '2021 SI QUAL LABO - SI LOGICIEL QUALITE LABO GHT'),
    ('2021 SI WIFI', '2021 SI WIFI - SI WIFI CHICAS'),
    ('2022 SE CD RENOUVLIT H', '2022 SE CD RENOUVLIT H - SE CD RENOUVELLEMENT LITS H'),
    ('2022-RENOV-DESENF-SISTE', '2022-RENOV-DESENF-SISTE - ST RENOVATION DESENFUMAGE SSR SISTERON'),
    ('2022-SI-CYBERSECURITE', '2022-SI-CYBERSECURITE - SI CYBERSECURITE'),
    ('2023-SI-PARCINFO', '2023-SI-PARCINFO - SI PARC INFO'),
    ('2023-ST-HELISTATION', '2023-ST-HELISTATION - ST HELISTATION'),
    ('2023-ST-SALLE10-BLOC', '2023-ST-SALLE10-BLOC - ST TRX AMENAGEMENT SALLE 10 DU BLOC OPERATOIRE GAP'),
    ('2023-ST-SCANNER2', '2023-ST-SCANNER2 - ST TRX D¿AMENAGEMENT SERVICE SCANNER 2 GAP'),
    ('2024-SE-FAUTEUILC15', '2024-SE-FAUTEUILC15 - SE Renouvellement fauteuil H24 Centre 15'),
    ('2025_HPR_SISTERON', '2025_HPR_SISTERON - Dotation 2025 HPR SISTERON'),
    ('AAP_PTEVENTION_MSA', 'AAP_PTEVENTION_MSA - Coup de pouce Prevention MSA'),
    ('AMI_Pensee_Plus', 'AMI_Pensee_Plus - AMI_Pensee_Plus transition énergétique'),
    ('DONS', 'DONS - DONS'),
    ('HPROX_S_AUTRE', 'HPROX_S_AUTRE - Autre'),
    ('HPROX_S_CSEXT', 'HPROX_S_CSEXT - Loc echog et renforcement des soins de proximité'),
    ('HPROX_S_URG', 'HPROX_S_URG - SAU: modernisation des équipements'),
    ('IQ2023_Soins_Palliatifs', 'IQ2023_Soins_Palliatifs - Investissements du quotidien 2023 Soins Palliatifs'),
    ('LSST', 'LSST - Lieu de Santé Sans Tabac'),
    ('PRIME_POLE_CHIRANESTREA_CHICAS_2025', 'PRIME_POLE_CHIRANESTREA_CHICAS_2025 - PRIME DE POLE 2025 CHIRURGIE ANESTE REA'),
    ('PRIME_POLE_FE_CHICAS_2025', 'PRIME_POLE_FE_CHICAS_2025 - PRIME DE POLE 2025 FEMME ENFANT'),
    ('PRIME_POLE_GERONTO_CHICAS_2025', 'PRIME_POLE_GERONTO_CHICAS_2025 - PRIME DE POLE 2025 GERONTO'),
    ('PRIME_POLE_MEDICAL_CHICAS_2025', 'PRIME_POLE_MEDICAL_CHICAS_2025 - PRIME DE POLE 2025 MEDICAL'),
    ('PRIME_POLE_MT_CHICAS_2025', 'PRIME_POLE_MT_CHICAS_2025 - PRIME DE POLE 2025 MEDICO TECH'),
    ('PRIME_POLE_SC_CHICAS_2025', 'PRIME_POLE_SC_CHICAS_2025 - PRIME DE POLE 2025 SOINS CRITIQUES'),
    ('SI-AUTOCOM', 'SI-AUTOCOM - AUTOCOM DIRECTION COMMUNE'),
    ('SI-CHIMIO', 'SI-CHIMIO - SI logiciel CHIMIOTHERAPIE'),
    ('SI-GMAO', 'SI-GMAO - SI LOGICIEL GMAO GHT'),
    ('SI-PHARMA', 'SI-PHARMA - SI log pharmacie sérialisation+migration Copil'),
    ('SI-QLABO', 'SI-QLABO - SI Logiciel Qualité LABO GHT'),
    ('SI-RIS', 'SI-RIS - SI logiciel RIS GHT'),
    ('SI-SAMU', 'SI-SAMU - SI SI SAMU'),
    ('VACC_HPV', 'VACC_HPV - Campagne de Vaccination HPV'),
    ('SI-BEDMAN', 'SI-BEDMAN - SI logiciel BEDMANAGER (subv 905833,19))'),
    ('SI-HMFORMS', 'SI-HMFORMS - SI logiciel HM FORMS'),
    ('AAP_ACC_ROUTE', 'AAP_ACC_ROUTE - AAP Accidentés de la route'),
]

UF_CHOICES = [
    ('', 'Sélectionnez un UF'),
    ('SERVICE SYSTEME D\'INFORMATION', 'SERVICE SYSTEME D\'INFORMATION'),
    ('GHT ALPES DU SUD', 'GHT ALPES DU SUD'),
    ('GHT ALPES DU SUD - SIH', 'GHT ALPES DU SUD - SIH'),
    ('GHT ALPES DU SUD - FORMATION CONTINUE DRH DAM', 'GHT ALPES DU SUD - FORMATION CONTINUE DRH DAM'),
    ('GHT ALPES DU SUD - ACHATS', 'GHT ALPES DU SUD - ACHATS'),
    ('GHT ALPES DU SUD - DIM', 'GHT ALPES DU SUD - DIM'),
    ('GHT ADS – SIH – GESTION DES LITS', 'GHT ADS – SIH – GESTION DES LITS'),
    ('GHT ALPES DU SUD – UAGSSE', 'GHT ALPES DU SUD – UAGSSE'),
    ('GHT ALPES DU SUD – Pharmacie', 'GHT ALPES DU SUD – Pharmacie'),
    ('GHT ADS – Urgences Embrun', 'GHT ADS – Urgences Embrun'),
    ('MàD PERSONNEL FACTURE', 'MàD PERSONNEL FACTURE'),
    ('DIRECTION GENERALE', 'DIRECTION GENERALE'),
    ('CLM - CLD', 'CLM - CLD'),
    ('S.M.A.R.T.', 'S.M.A.R.T.'),
    ('DIRECTION DES SOINS', 'DIRECTION DES SOINS'),
    ('CENTRALE D\'APPELS - SEC MEDICAUX', 'CENTRALE D\'APPELS - SEC MEDICAUX'),
    ('CENTRALE DE FRAPPE - SEC MEDICAUX', 'CENTRALE DE FRAPPE - SEC MEDICAUX'),
    ('AGDUC', 'AGDUC'),
    ('UGECAM GAP', 'UGECAM GAP'),
    ('AIDE AU RETOUR A L\'EMPLOI (ARE)', 'AIDE AU RETOUR A L\'EMPLOI (ARE)'),
    ('SERVICE DIETETIQUE', 'SERVICE DIETETIQUE'),
    ('PSYCHOLOGUE', 'PSYCHOLOGUE'),
    ('SERVICE AUDIOVISUEL - TELEPHONIE SISTERON', 'SERVICE AUDIOVISUEL - TELEPHONIE SISTERON'),
    ('SERVICE AUDIOVISUEL - TELEPHONIE GAP', 'SERVICE AUDIOVISUEL - TELEPHONIE GAP'),
    ('SERV AUDIO TEL SISTERON', 'SERV AUDIO TEL SISTERON'),
    ('SERV AUDIO TEL GAP', 'SERV AUDIO TEL GAP'),
    ('SERVICE DIETETIQUE - S', 'SERVICE DIETETIQUE - S'),
    ('HOSP TEMPS PART SPE MED 1 - S', 'HOSP TEMPS PART SPE MED 1 - S'),
    ('HOSP TEMPS PARTIEL NUIT - S', 'HOSP TEMPS PARTIEL NUIT - S'),
    ('MEDECINE 2 COVID - S (HC)', 'MEDECINE 2 COVID - S (HC)'),
    ('TELEMEDECINE MEDECINE INTERNE (C)', 'TELEMEDECINE MEDECINE INTERNE (C)'),
    ('MEDECINE LEGALE (C)', 'MEDECINE LEGALE (C)'),
    ('ONCO-HEMATO HDJ MEDECINE (C)', 'ONCO-HEMATO HDJ MEDECINE (C)'),
    ('TELEMEDECINE ONCO HEMATO HDJ (C)', 'TELEMEDECINE ONCO HEMATO HDJ (C)'),
    ('CHIR 1 UNITE D\'EXTENSION (HC)', 'CHIR 1 UNITE D\'EXTENSION (HC)'),
    ('UNITE GERIATRIQUE SAISONNIERE (HC)', 'UNITE GERIATRIQUE SAISONNIERE (HC)'),
    ('COVID 19 (C)', 'COVID 19 (C)'),
    ('OPHTALMOLOGIE - S (C)', 'OPHTALMOLOGIE - S (C)'),
    ('MEDECINE GERIATRIQUE (HC)', 'MEDECINE GERIATRIQUE (HC)'),
    ('MEDECINE GERIATRIQUE 3 - (HC)', 'MEDECINE GERIATRIQUE 3 - (HC)'),
    ('COVID GERIATRIQUE (HC)', 'COVID GERIATRIQUE (HC)'),
    ('HDJ ONCO GERIATRIE (HJ) HORS SEANCES', 'HDJ ONCO GERIATRIE (HJ) HORS SEANCES'),
    ('HOPITAL DE JOUR DE GERIATRIE', 'HOPITAL DE JOUR DE GERIATRIE'),
    ('ONCO GERIATRIE (C)', 'ONCO GERIATRIE (C)'),
    ('TELEMEDECINE GERIATRIQUE', 'TELEMEDECINE GERIATRIQUE'),
    ('TELESURVEILLANCE ONCOLOGIQUE (C)', 'TELESURVEILLANCE ONCOLOGIQUE (C)'),
    ('IPA ONCOLOGIE (C)', 'IPA ONCOLOGIE (C)'),
    ('EQUIPE MOBILE DE GERIATRIE', 'EQUIPE MOBILE DE GERIATRIE'),
    ('UNITE GERIATRIQUE URGENCE', 'UNITE GERIATRIQUE URGENCE'),
    ('EQUIPE MOBILE DE GERIATRIE Extrahospitalière', 'EQUIPE MOBILE DE GERIATRIE Extrahospitalière'),
    ('EQUIPE MOBILE DE GERIATRIE', 'EQUIPE MOBILE DE GERIATRIE'),
    ('ATELIER MASSAGE NOUVEAU NE ( C )', 'ATELIER MASSAGE NOUVEAU NE ( C )'),
    ('TELEMEDECINE PEDIATRIE (C)', 'TELEMEDECINE PEDIATRIE (C)'),
    ('UAPED (C) – Unité d’Accueil Pédiatrique Enfants en Danger', 'UAPED (C) – Unité d’Accueil Pédiatrique Enfants en Danger'),
    ('PEDIATRIE (C) - S', 'PEDIATRIE (C) - S'),
    ('GASTRO-ENTEROLOGIE (HC)', 'GASTRO-ENTEROLOGIE (HC)'),
    ('EXPLORATION FONCTION. TUBE DIGESTIF', 'EXPLORATION FONCTION. TUBE DIGESTIF'),
    ('EXPLO FONCT TUBE DIGESTIF', 'EXPLO FONCT TUBE DIGESTIF'),
    ('TELEMEDECINE GASTRO-ENTEROLOGIE (C)', 'TELEMEDECINE GASTRO-ENTEROLOGIE (C)'),
    ('RHUMATOLOGIE (C)', 'RHUMATOLOGIE (C)'),
    ('GASTRO-ENTEROLOGIE (C) - S', 'GASTRO-ENTEROLOGIE (C) - S'),
    ('CARDIOLOGIE (HC)', 'CARDIOLOGIE (HC)'),
    ('SURV CONT CARDIOLOGIE (HC)', 'SURV CONT CARDIOLOGIE (HC)'),
    ('CARDIOLOGIE (HC) CHIR 1', 'CARDIOLOGIE (HC) CHIR 1'),
    ('HOPITAL DE JOUR DE CARDIOLOGIE', 'HOPITAL DE JOUR DE CARDIOLOGIE'),
    ('HOSP TEMPS PART SPE MED 1 - S', 'HOSP TEMPS PART SPE MED 1 - S'),
    ('HOSP TEMPS PART SPE MED 2 - S', 'HOSP TEMPS PART SPE MED 2 - S'),
    ('EQUIPE MOBILE INSUFFISANT CARDIAQUE', 'EQUIPE MOBILE INSUFFISANT CARDIAQUE'),
    ('TELE EXPERTISE CARDIO (C)', 'TELE EXPERTISE CARDIO (C)'),
    ('TELESURVEILLANCE CARDIAQUE ( C ) (ex Telémedecine Cardio)', 'TELESURVEILLANCE CARDIAQUE ( C ) (ex Telémedecine Cardio)'),
    ('ENDOCRINO-DIABETO (C)', 'ENDOCRINO-DIABETO (C)'),
    ('ENDOCRINO-DIABETO (C) – S', 'ENDOCRINO-DIABETO (C) – S'),
    ('SERVICES DE SOINS SUPPORT T D\'ACCOMPAGNEMENT (HC)', 'SERVICES DE SOINS SUPPORT T D\'ACCOMPAGNEMENT (HC)'),
    ('SERVICES DE SOINS SUPPORT D\'ACCOMPAGNEMENT (HC)', 'SERVICES DE SOINS SUPPORT D\'ACCOMPAGNEMENT (HC)'),
    ('EQUIPE MOBILE DE SOINS PALLIATIFS', 'EQUIPE MOBILE DE SOINS PALLIATIFS'),
    ('HÔPITAL DE NUIT DE PNEUMOLOGIE', 'HÔPITAL DE NUIT DE PNEUMOLOGIE'),
    ('PNEUMOLOGIE (HC) COVID+', 'PNEUMOLOGIE (HC) COVID+'),
    ('ESSAIS CLINIQUES', 'ESSAIS CLINIQUES'),
    ('TELEMEDECINE PNEUMOLOGIE (C)', 'TELEMEDECINE PNEUMOLOGIE (C)'),
    ('THERAPIE COGNITIVO COMPORTEMENTALE (C)', 'THERAPIE COGNITIVO COMPORTEMENTALE (C)'),
    ('TELEMEDECINE ADDICTOLOGIE (C)', 'TELEMEDECINE ADDICTOLOGIE (C)'),
    ('CHIR ORTHO & SPEC (HC) HEB', 'CHIR ORTHO & SPEC (HC) HEB'),
    ('CHIR ORTHO TRAUMATOLOGIE (HC)', 'CHIR ORTHO TRAUMATOLOGIE (HC)'),
    ('CHIRURGIE ORTHO/TRAUMATO (HC)', 'CHIRURGIE ORTHO/TRAUMATO (HC)'),
    ('CHIRURGIE SPECIALITES (ORL OPH ALGO STOMATO) (HC)', 'CHIRURGIE SPECIALITES (ORL OPH ALGO STOMATO) (HC)'),
    ('CHIRURGIE ORL & ORALE (HC)', 'CHIRURGIE ORL & ORALE (HC)'),
    ('CHIRURGIE OPHTALMOLOGIE (HC)', 'CHIRURGIE OPHTALMOLOGIE (HC)'),
    ('CHIRURGIE ALGOLOGIE (HC)', 'CHIRURGIE ALGOLOGIE (HC)'),
    ('TELEMEDECINE CHIRURGIE UROLOGIQUE (C)', 'TELEMEDECINE CHIRURGIE UROLOGIQUE (C)'),
    ('TELEMEDECINE CHIRURGIE VISCERALE (C)', 'TELEMEDECINE CHIRURGIE VISCERALE (C)'),
    ('TELEMEDECINE CHIRURGIE ORTHO/TRAUMATOLOGIQUE (C)', 'TELEMEDECINE CHIRURGIE ORTHO/TRAUMATOLOGIQUE (C)'),
    ('CHIRURGIE UROLOGIQUE - S (C)', 'CHIRURGIE UROLOGIQUE - S (C)'),
    ('CHIRURGIE ORTHOPEDIQUE - S ( C )', 'CHIRURGIE ORTHOPEDIQUE - S ( C )'),
    ('CHIRURGIE VISCERALE - S (C)', 'CHIRURGIE VISCERALE - S (C)'),
    ('PNEUMOLOGIE - S (C)', 'PNEUMOLOGIE - S (C)'),
    ('CHIRURGIE ORL - S ( C )', 'CHIRURGIE ORL - S ( C )'),
    ('OBSTETRIQUE NN (HC)', 'OBSTETRIQUE NN (HC)'),
    ('OBSTETRIQUE SAGE-FEMME (C)', 'OBSTETRIQUE SAGE-FEMME (C)'),
    ('COSMETOLOGIE MEDICALE (C)', 'COSMETOLOGIE MEDICALE (C)'),
    ('CHIR VISC - URO - GYNECO (HC) HEB', 'CHIR VISC - URO - GYNECO (HC) HEB'),
    ('CHIRURGIE URO & GYNECO', 'CHIRURGIE URO & GYNECO'),
    ('CHIRURGIE POLYVALENTE 1 (HC)', 'CHIRURGIE POLYVALENTE 1 (HC)'),
    ('CHIRURGIE UROLOGIE (HC)', 'CHIRURGIE UROLOGIE (HC)'),
    ('GYNECOLOGIE CHIRURGICALE (HC)', 'GYNECOLOGIE CHIRURGICALE (HC)'),
    ('CHIR URO VISCERALE (HC)', 'CHIR URO VISCERALE (HC)'),
    ('USLD 1 GAP', 'USLD 1 GAP'),
    ('USLD 1 GAP - SOINS', 'USLD 1 GAP - SOINS'),
    ('USLD 1 GAP - DEPENDANCE', 'USLD 1 GAP - DEPENDANCE'),
    ('UHPAD - S', 'UHPAD - S'),
    ('UHPAD - S - PASA - SOINS', 'UHPAD - S - PASA - SOINS'),
    ('UHPAD - S Hébergement 1', 'UHPAD - S Hébergement 1'),
    ('UHPAD - S Hébergement 2', 'UHPAD - S Hébergement 2'),
    ('UHPAD - S Hébergement 3', 'UHPAD - S Hébergement 3'),
    ('USLD 3 GAP', 'USLD 3 GAP'),
    ('USLD 3 GAP SOINS', 'USLD 3 GAP SOINS'),
    ('USLD 3 GAP DEPENDANCE', 'USLD 3 GAP DEPENDANCE'),
    ('USLD 2 GAP - UHR', 'USLD 2 GAP - UHR'),
    ('USLD 2 GAP - UHR - SOINS', 'USLD 2 GAP - UHR - SOINS'),
    ('USLD 2 GAP - UHR - DEPENDANCE', 'USLD 2 GAP - UHR - DEPENDANCE'),
    ('UHPAD - GAP', 'UHPAD - GAP'),
    ('UHPAD- GAP SOINS', 'UHPAD- GAP SOINS'),
    ('UHPAD - GAP DEPENDANCE', 'UHPAD - GAP DEPENDANCE'),
    ('EQUIPE POLYVALENTS - SEC MEDICAUX', 'EQUIPE POLYVALENTS - SEC MEDICAUX'),
    ('UHTCD 2 (HC) - CHIR 1', 'UHTCD 2 (HC) - CHIR 1'),
    ('S.M.U. (C)', 'S.M.U. (C)'),
    ('URGENCES GAP (C)', 'URGENCES GAP (C)'),
    ('CONSULTATION POST URGENCE ©', 'CONSULTATION POST URGENCE ©'),
    ('VIOLENCES FAITES AUX FEMMES', 'VIOLENCES FAITES AUX FEMMES'),
    ('DEPISTAGE COVID 19 (C)', 'DEPISTAGE COVID 19 (C)'),
    ('MEDECINS CORRESPONDANT SAMU', 'MEDECINS CORRESPONDANT SAMU'),
    ('UMSP RV', 'UMSP RV'),
    ('PASS Mobile', 'PASS Mobile'),
    ('USMP', 'USMP'),
    ('UHTCD - S (HC)', 'UHTCD - S (HC)'),
    ('UHTCD COVID - S (HC)', 'UHTCD COVID - S (HC)'),
    ('S.M.U. - S (C)', 'S.M.U. - S (C)'),
    ('URGENCES SISTERON (C)', 'URGENCES SISTERON (C)'),
    ('REANIMATION SSPI 2 (HEB)', 'REANIMATION SSPI 2 (HEB)'),
    ('SURV CONTINUE POLY OPTIFLOW (HC)', 'SURV CONTINUE POLY OPTIFLOW (HC)'),
    ('SURVEILLANCE CONTINUE 2 SSPI (HEB)', 'SURVEILLANCE CONTINUE 2 SSPI (HEB)'),
    ('MAISON MEDICALE DE GARDE (C)', 'MAISON MEDICALE DE GARDE (C)'),
    ('TELEMEDECINE DIALYSE (C)', 'TELEMEDECINE DIALYSE (C)'),
    ('DIALYSE (C) - S', 'DIALYSE (C) - S'),
    ('KINESITHERAPIE - ADRET GERONTOLOGIE', 'KINESITHERAPIE - ADRET GERONTOLOGIE'),
    ('CUISINE EDUCATIVE GERONTOLOGIE', 'CUISINE EDUCATIVE GERONTOLOGIE'),
    ('ERGOTHERAPIE GERONTOLOGIE', 'ERGOTHERAPIE GERONTOLOGIE'),
    ('ORTHOGENIE (C)', 'ORTHOGENIE (C)'),
    ('PSYCHIATRIE SECTEUR (C)', 'PSYCHIATRIE SECTEUR (C)'),
    ('SERVICE DE SANTE AU TRAVAIL', 'SERVICE DE SANTE AU TRAVAIL'),
    ('MISE A DISPO SYND NAT & LOC', 'MISE A DISPO SYND NAT & LOC'),
    ('I.R.M. 1 PUBLIC', 'I.R.M. 1 PUBLIC'),
    ('OSTEODENSITOMETRIE', 'OSTEODENSITOMETRIE'),
    ('RADIOTHERAPIE (C)', 'RADIOTHERAPIE (C)'),
    ('RADIOTHERAPIE (SIMULATION)', 'RADIOTHERAPIE (SIMULATION)'),
    ('ECHOGRAPHIE - S', 'ECHOGRAPHIE - S'),
    ('LABORATOIRE - ETS EXTERIEURS', 'LABORATOIRE - ETS EXTERIEURS'),
    ('LABORATOIRE TERRITORIAL (C)', 'LABORATOIRE TERRITORIAL (C)'),
    ('LABORATOIRE - GAP', 'LABORATOIRE - GAP'),
    ('LABORATOIRE - CH BRIANCON', 'LABORATOIRE - CH BRIANCON'),
    ('LABORATOIRE  - SISTERON', 'LABORATOIRE  - SISTERON'),
    ('CHIRURGIE ORALE (C)', 'CHIRURGIE ORALE (C)'),
    ('BLOC ORTHO/TRAUMATOLOGIQUE', 'BLOC ORTHO/TRAUMATOLOGIQUE'),
    ('BLOC CHIRURGIE VISCERALE', 'BLOC CHIRURGIE VISCERALE'),
    ('BLOC CHIRURGIE UROLOGIQUE', 'BLOC CHIRURGIE UROLOGIQUE'),
    ('BLOC CHIRURGIE ORALE', 'BLOC CHIRURGIE ORALE'),
    ('BLOC CHIR VISCERALE', 'BLOC CHIR VISCERALE'),
    ('BLOC CHIR UROLOGIQUE', 'BLOC CHIR UROLOGIQUE'),
    ('BLOC ORTHO/TRAUMATOLOGIQUE', 'BLOC ORTHO/TRAUMATOLOGIQUE'),
    ('ALGOLOGIE (C) - S', 'ALGOLOGIE (C) - S'),
    ('TELEMEDECINE ALGOLOGIE (C)', 'TELEMEDECINE ALGOLOGIE (C)'),
    ('C.F.P.S. - PREPA CONCOURS IDE', 'C.F.P.S. - PREPA CONCOURS IDE'),
    ('C.F.P.S. - PREPA CONCOURS AS', 'C.F.P.S. - PREPA CONCOURS AS'),
    ('C.F.P.S. - FORMATION CONTINUE', 'C.F.P.S. - FORMATION CONTINUE'),
    ('HOSPITALISATION A DOMICILE', 'HOSPITALISATION A DOMICILE'),
    ('CEGGID & IST', 'CEGGID & IST'),
    ('CENTRE VACCINATION COVID 19 (C)', 'CENTRE VACCINATION COVID 19 (C)'),
    ('CENTRE VACCINATION COVID 19 - S (C)', 'CENTRE VACCINATION COVID 19 - S (C)'),
    ('CENTRE VACCINATION COVID 19 - CMCL', 'CENTRE VACCINATION COVID 19 - CMCL'),
    ('HOPITAL DE JOUR DE MEDECINE', 'HOPITAL DE JOUR DE MEDECINE'),
    ('HDJ PNEUMO GASTRO', 'HDJ PNEUMO GASTRO'),
    ('CHIRURGIE AMBULATOIRE (HJ)', 'CHIRURGIE AMBULATOIRE (HJ)'),
    ('CHIR AMBU - UROLOGIE', 'CHIR AMBU - UROLOGIE'),
    ('CHIR AMBU - ORTHO-TRAUMATOLOGIE', 'CHIR AMBU - ORTHO-TRAUMATOLOGIE'),
    ('CHIR AMBU - VISCERALE', 'CHIR AMBU - VISCERALE'),
    ('CHIR AMBU - OPHTALMOLOGIE', 'CHIR AMBU - OPHTALMOLOGIE'),
    ('CHIR AMBU ORL & ORALE', 'CHIR AMBU ORL & ORALE'),
    ('CHIR AMBU - ALGOLOGIE', 'CHIR AMBU - ALGOLOGIE'),
    ('CHIR AMBU - GYNECOLOGIE', 'CHIR AMBU - GYNECOLOGIE'),
    ('CHIR AMBU - GASTRO-ENTEROLOGIE', 'CHIR AMBU - GASTRO-ENTEROLOGIE'),
    ('CHIR AMBU - CARDIOLOGIE', 'CHIR AMBU - CARDIOLOGIE'),
    ('CHIR AMBU - PNEUMOLOGIE', 'CHIR AMBU - PNEUMOLOGIE'),
    ('I.R.M. 2 PRIVE', 'I.R.M. 2 PRIVE'),
    ('MEDECINS DU MONDE PRESTATIONS', 'MEDECINS DU MONDE PRESTATIONS'),
    ('GIE IRM', 'GIE IRM'),
    ('POLYCLINIQUE ALPES DU SUD PRESTATIONS', 'POLYCLINIQUE ALPES DU SUD PRESTATIONS'),
    ('BLANCHISSERIE GCS (PLATEFORME HOSP 05)', 'BLANCHISSERIE GCS (PLATEFORME HOSP 05)'),
    ('SERVICE DIETETIQUE', 'SERVICE DIETETIQUE'),
    ('DISTRIBUTION/COLLECTES CHICAS INTERNE', 'DISTRIBUTION/COLLECTES CHICAS INTERNE'),
    ('DISTRIB/COLLECTES CHICAS EXTERNE', 'DISTRIB/COLLECTES CHICAS EXTERNE'),
    ('GARAGE', 'GARAGE'),
    ('SERVICE BIOMEDICAL - DM STOCK DE CRISE', 'SERVICE BIOMEDICAL - DM STOCK DE CRISE'),
    ('LINGERIE BLANCHISSERIE - GAP', 'LINGERIE BLANCHISSERIE - GAP'),
    ('DISTRIBUTION/COLLECTES GCS (PLATEFORME HOSP 05)', 'DISTRIBUTION/COLLECTES GCS (PLATEFORME HOSP 05)'),
    ('DEMENAGEMENT MANUTENTION', 'DEMENAGEMENT MANUTENTION'),
    ('DENEIGEMENT', 'DENEIGEMENT'),
    ('SMR GERIATRIQUE', 'SMR GERIATRIQUE'),
    ('SMR - UCC', 'SMR - UCC'),
    ('SMR SPECIALISE - S (HJ)', 'SMR SPECIALISE - S (HJ)'),
    ('SMR INDIFFERENCIE - S (HC)', 'SMR INDIFFERENCIE - S (HC)'),
    ('CESU Embrun', 'CESU Embrun'),
    ('MAGASIN PHARMACIE - PRÊT', 'MAGASIN PHARMACIE - PRÊT'),
    ('MAGASIN LABORATOIRE - B Effet au 11/12/2023', 'MAGASIN LABORATOIRE - B Effet au 11/12/2023'),
    ('BONI MAGASIN - S', 'BONI MAGASIN - S'),
    ('BONI PHARMACIE - S', 'BONI PHARMACIE - S'),
    ('BONI MAGASIN ECONOMAT - S', 'BONI MAGASIN ECONOMAT - S'),
    ('BONI MAGASIN LABORATOIRE - S', 'BONI MAGASIN LABORATOIRE - S'),
    ('BONI MAGASIN GENERAL', 'BONI MAGASIN GENERAL'),
    ('BONI MAG.PHARMACIE', 'BONI MAG.PHARMACIE'),
    ('BONI MAG LABORATOIRE', 'BONI MAG LABORATOIRE'),
    ('BONI MAG.ALIMENTATION', 'BONI MAG.ALIMENTATION'),
]

UF_CHOICES = [
    ('', 'Sélectionnez un UF'),
    ('SERVICE SYSTEME D\'INFORMATION', 'SERVICE SYSTEME D\'INFORMATION'),
    ('GHT ALPES DU SUD', 'GHT ALPES DU SUD'),
    ('GHT ALPES DU SUD - SIH', 'GHT ALPES DU SUD - SIH'),
    ('GHT ALPES DU SUD - FORMATION CONTINUE DRH DAM', 'GHT ALPES DU SUD - FORMATION CONTINUE DRH DAM'),
    ('GHT ALPES DU SUD - ACHATS', 'GHT ALPES DU SUD - ACHATS'),
    ('GHT ALPES DU SUD - DIM', 'GHT ALPES DU SUD - DIM'),
    ('GHT ADS – SIH – GESTION DES LITS', 'GHT ADS – SIH – GESTION DES LITS'),
    ('GHT ALPES DU SUD – UAGSSE', 'GHT ALPES DU SUD – UAGSSE'),
    ('GHT ALPES DU SUD – Pharmacie', 'GHT ALPES DU SUD – Pharmacie'),
    ('GHT ADS – Urgences Embrun', 'GHT ADS – Urgences Embrun'),
    ('MàD PERSONNEL FACTURE', 'MàD PERSONNEL FACTURE'),
    ('DIRECTION GENERALE', 'DIRECTION GENERALE'),
    ('CLM - CLD', 'CLM - CLD'),
    ('S.M.A.R.T.', 'S.M.A.R.T.'),
    ('DIRECTION DES SOINS', 'DIRECTION DES SOINS'),
    ('CENTRALE D\'APPELS - SEC MEDICAUX', 'CENTRALE D\'APPELS - SEC MEDICAUX'),
    ('CENTRALE DE FRAPPE - SEC MEDICAUX', 'CENTRALE DE FRAPPE - SEC MEDICAUX'),
    ('AGDUC', 'AGDUC'),
    ('UGECAM GAP', 'UGECAM GAP'),
    ('AIDE AU RETOUR A L\'EMPLOI (ARE)', 'AIDE AU RETOUR A L\'EMPLOI (ARE)'),
    ('SERVICE DIETETIQUE', 'SERVICE DIETETIQUE'),
    ('PSYCHOLOGUE', 'PSYCHOLOGUE'),
    ('SERVICE AUDIOVISUEL - TELEPHONIE SISTERON', 'SERVICE AUDIOVISUEL - TELEPHONIE SISTERON'),
    ('SERVICE AUDIOVISUEL - TELEPHONIE GAP', 'SERVICE AUDIOVISUEL - TELEPHONIE GAP'),
    ('SERV AUDIO TEL SISTERON', 'SERV AUDIO TEL SISTERON'),
    ('SERV AUDIO TEL GAP', 'SERV AUDIO TEL GAP'),
    ('SERVICE DIETETIQUE - S', 'SERVICE DIETETIQUE - S'),
    ('HOSP TEMPS PART SPE MED 1 - S', 'HOSP TEMPS PART SPE MED 1 - S'),
    ('HOSP TEMPS PARTIEL NUIT - S', 'HOSP TEMPS PARTIEL NUIT - S'),
    ('MEDECINE 2 COVID - S (HC)', 'MEDECINE 2 COVID - S (HC)'),
    ('TELEMEDECINE MEDECINE INTERNE (C)', 'TELEMEDECINE MEDECINE INTERNE (C)'),
    ('MEDECINE LEGALE (C)', 'MEDECINE LEGALE (C)'),
    ('ONCO-HEMATO HDJ MEDECINE (C)', 'ONCO-HEMATO HDJ MEDECINE (C)'),
    ('TELEMEDECINE ONCO HEMATO HDJ (C)', 'TELEMEDECINE ONCO HEMATO HDJ (C)'),
    ('CHIR 1 UNITE D\'EXTENSION (HC)', 'CHIR 1 UNITE D\'EXTENSION (HC)'),
    ('UNITE GERIATRIQUE SAISONNIERE (HC)', 'UNITE GERIATRIQUE SAISONNIERE (HC)'),
    ('COVID 19 (C)', 'COVID 19 (C)'),
    ('OPHTALMOLOGIE - S (C)', 'OPHTALMOLOGIE - S (C)'),
    ('MEDECINE GERIATRIQUE (HC)', 'MEDECINE GERIATRIQUE (HC)'),
    ('MEDECINE GERIATRIQUE 3 - (HC)', 'MEDECINE GERIATRIQUE 3 - (HC)'),
    ('COVID GERIATRIQUE (HC)', 'COVID GERIATRIQUE (HC)'),
    ('HDJ ONCO GERIATRIE (HJ) HORS SEANCES', 'HDJ ONCO GERIATRIE (HJ) HORS SEANCES'),
    ('HOPITAL DE JOUR DE GERIATRIE', 'HOPITAL DE JOUR DE GERIATRIE'),
    ('ONCO GERIATRIE (C)', 'ONCO GERIATRIE (C)'),
    ('TELEMEDECINE GERIATRIQUE', 'TELEMEDECINE GERIATRIQUE'),
    ('TELESURVEILLANCE ONCOLOGIQUE (C)', 'TELESURVEILLANCE ONCOLOGIQUE (C)'),
    ('IPA ONCOLOGIE (C)', 'IPA ONCOLOGIE (C)'),
    ('EQUIPE MOBILE DE GERIATRIE', 'EQUIPE MOBILE DE GERIATRIE'),
    ('UNITE GERIATRIQUE URGENCE', 'UNITE GERIATRIQUE URGENCE'),
    ('EQUIPE MOBILE DE GERIATRIE Extrahospitalière', 'EQUIPE MOBILE DE GERIATRIE Extrahospitalière'),
    ('EQUIPE MOBILE DE GERIATRIE', 'EQUIPE MOBILE DE GERIATRIE'),
    ('ATELIER MASSAGE NOUVEAU NE ( C )', 'ATELIER MASSAGE NOUVEAU NE ( C )'),
    ('TELEMEDECINE PEDIATRIE (C)', 'TELEMEDECINE PEDIATRIE (C)'),
    ('UAPED (C) – Unité d’Accueil Pédiatrique Enfants en Danger', 'UAPED (C) – Unité d’Accueil Pédiatrique Enfants en Danger'),
    ('PEDIATRIE (C) - S', 'PEDIATRIE (C) - S'),
    ('GASTRO-ENTEROLOGIE (HC)', 'GASTRO-ENTEROLOGIE (HC)'),
    ('EXPLORATION FONCTION. TUBE DIGESTIF', 'EXPLORATION FONCTION. TUBE DIGESTIF'),
    ('EXPLO FONCT TUBE DIGESTIF', 'EXPLO FONCT TUBE DIGESTIF'),
    ('GASTRO-ENTEROLOGIE (HC)', 'GASTRO-ENTEROLOGIE (HC)'),
    ('TELEMEDECINE GASTRO-ENTEROLOGIE (C)', 'TELEMEDECINE GASTRO-ENTEROLOGIE (C)'),
    ('RHUMATOLOGIE (C)', 'RHUMATOLOGIE (C)'),
    ('GASTRO-ENTEROLOGIE (C) - S', 'GASTRO-ENTEROLOGIE (C) - S'),
    ('CARDIOLOGIE (HC)', 'CARDIOLOGIE (HC)'),
    ('SURV CONT CARDIOLOGIE (HC)', 'SURV CONT CARDIOLOGIE (HC)'),
    ('CARDIOLOGIE (HC)', 'CARDIOLOGIE (HC)'),
    ('CARDIOLOGIE (HC) CHIR 1', 'CARDIOLOGIE (HC) CHIR 1'),
    ('HOPITAL DE JOUR DE CARDIOLOGIE', 'HOPITAL DE JOUR DE CARDIOLOGIE'),
    ('HOSP TEMPS PART SPE MED 1 - S', 'HOSP TEMPS PART SPE MED 1 - S'),
    ('HOSP TEMPS PART SPE MED 2 - S', 'HOSP TEMPS PART SPE MED 2 - S'),
    ('EQUIPE MOBILE INSUFFISANT CARDIAQUE', 'EQUIPE MOBILE INSUFFISANT CARDIAQUE'),
    ('TELE EXPERTISE CARDIO (C)', 'TELE EXPERTISE CARDIO (C)'),
    ('TELESURVEILLANCE CARDIAQUE ( C ) (ex Telémedecine Cardio)', 'TELESURVEILLANCE CARDIAQUE ( C ) (ex Telémedecine Cardio)'),
    ('ENDOCRINO-DIABETO (C)', 'ENDOCRINO-DIABETO (C)'),
    ('ENDOCRINO-DIABETO (C) – S', 'ENDOCRINO-DIABETO (C) – S'),
    ('SERVICES DE SOINS SUPPORT T D\'ACCOMPAGNEMENT (HC)', 'SERVICES DE SOINS SUPPORT T D\'ACCOMPAGNEMENT (HC)'),
    ('SERVICES DE SOINS SUPPORT D\'ACCOMPAGNEMENT (HC)', 'SERVICES DE SOINS SUPPORT D\'ACCOMPAGNEMENT (HC)'),
    ('EQUIPE MOBILE DE SOINS PALLIATIFS', 'EQUIPE MOBILE DE SOINS PALLIATIFS'),
    ('HÔPITAL DE NUIT DE PNEUMOLOGIE', 'HÔPITAL DE NUIT DE PNEUMOLOGIE'),
    ('PNEUMOLOGIE (HC) COVID+', 'PNEUMOLOGIE (HC) COVID+'),
    ('ESSAIS CLINIQUES', 'ESSAIS CLINIQUES'),
    ('TELEMEDECINE PNEUMOLOGIE (C)', 'TELEMEDECINE PNEUMOLOGIE (C)'),
    ('THERAPIE COGNITIVO COMPORTEMENTALE (C)', 'THERAPIE COGNITIVO COMPORTEMENTALE (C)'),
    ('TELEMEDECINE ADDICTOLOGIE (C)', 'TELEMEDECINE ADDICTOLOGIE (C)'),
    ('CHIR ORTHO & SPEC (HC) HEB', 'CHIR ORTHO & SPEC (HC) HEB'),
    ('CHIR ORTHO TRAUMATOLOGIE (HC)', 'CHIR ORTHO TRAUMATOLOGIE (HC)'),
    ('CHIRURGIE ORTHO/TRAUMATO (HC)', 'CHIRURGIE ORTHO/TRAUMATO (HC)'),
    ('CHIRURGIE SPECIALITES (ORL OPH ALGO STOMATO) (HC)', 'CHIRURGIE SPECIALITES (ORL OPH ALGO STOMATO) (HC)'),
    ('CHIRURGIE ORL & ORALE (HC)', 'CHIRURGIE ORL & ORALE (HC)'),
    ('CHIRURGIE OPHTALMOLOGIE (HC)', 'CHIRURGIE OPHTALMOLOGIE (HC)'),
    ('CHIRURGIE ALGOLOGIE (HC)', 'CHIRURGIE ALGOLOGIE (HC)'),
    ('TELEMEDECINE CHIRURGIE UROLOGIQUE (C)', 'TELEMEDECINE CHIRURGIE UROLOGIQUE (C)'),
    ('TELEMEDECINE CHIRURGIE VISCERALE (C)', 'TELEMEDECINE CHIRURGIE VISCERALE (C)'),
    ('TELEMEDECINE CHIRURGIE ORTHO/TRAUMATOLOGIQUE (C)', 'TELEMEDECINE CHIRURGIE ORTHO/TRAUMATOLOGIQUE (C)'),
    ('CHIRURGIE UROLOGIQUE - S (C)', 'CHIRURGIE UROLOGIQUE - S (C)'),
    ('CHIRURGIE ORTHOPEDIQUE - S ( C )', 'CHIRURGIE ORTHOPEDIQUE - S ( C )'),
    ('CHIRURGIE VISCERALE - S (C)', 'CHIRURGIE VISCERALE - S (C)'),
    ('PNEUMOLOGIE - S (C)', 'PNEUMOLOGIE - S (C)'),
    ('CHIRURGIE ORL - S ( C )', 'CHIRURGIE ORL - S ( C )'),
    ('OBSTETRIQUE NN (HC)', 'OBSTETRIQUE NN (HC)'),
    ('OBSTETRIQUE SAGE-FEMME (C)', 'OBSTETRIQUE SAGE-FEMME (C)'),
    ('COSMETOLOGIE MEDICALE (C)', 'COSMETOLOGIE MEDICALE (C)'),
    ('CHIR VISC - URO - GYNECO (HC) HEB', 'CHIR VISC - URO - GYNECO (HC) HEB'),
    ('CHIRURGIE URO & GYNECO', 'CHIRURGIE URO & GYNECO'),
    ('CHIRURGIE POLYVALENTE 1 (HC)', 'CHIRURGIE POLYVALENTE 1 (HC)'),
    ('CHIRURGIE UROLOGIE (HC)', 'CHIRURGIE UROLOGIE (HC)'),
    ('GYNECOLOGIE CHIRURGICALE (HC)', 'GYNECOLOGIE CHIRURGICALE (HC)'),
    ('CHIR URO VISCERALE (HC)', 'CHIR URO VISCERALE (HC)'),
    ('USLD 1 GAP', 'USLD 1 GAP'),
    ('USLD 1 GAP - SOINS', 'USLD 1 GAP - SOINS'),
    ('USLD 1 GAP - DEPENDANCE', 'USLD 1 GAP - DEPENDANCE'),
    ('UHPAD - S', 'UHPAD - S'),
    ('UHPAD - S - PASA - SOINS', 'UHPAD - S - PASA - SOINS'),
    ('UHPAD - S Hébergement 1', 'UHPAD - S Hébergement 1'),
    ('UHPAD - S Hébergement 2', 'UHPAD - S Hébergement 2'),
    ('UHPAD - S Hébergement 3', 'UHPAD - S Hébergement 3'),
    ('USLD 3 GAP', 'USLD 3 GAP'),
    ('USLD 3 GAP SOINS', 'USLD 3 GAP SOINS'),
    ('USLD 3 GAP DEPENDANCE', 'USLD 3 GAP DEPENDANCE'),
    ('USLD 2 GAP - UHR', 'USLD 2 GAP - UHR'),
    ('USLD 2 GAP - UHR - SOINS', 'USLD 2 GAP - UHR - SOINS'),
    ('USLD 2 GAP - UHR - DEPENDANCE', 'USLD 2 GAP - UHR - DEPENDANCE'),
    ('UHPAD - GAP', 'UHPAD - GAP'),
    ('UHPAD- GAP SOINS', 'UHPAD- GAP SOINS'),
    ('UHPAD - GAP DEPENDANCE', 'UHPAD - GAP DEPENDANCE'),
    ('EQUIPE POLYVALENTS - SEC MEDICAUX', 'EQUIPE POLYVALENTS - SEC MEDICAUX'),
    ('UHTCD 2 (HC) - CHIR 1', 'UHTCD 2 (HC) - CHIR 1'),
    ('S.M.U. (C)', 'S.M.U. (C)'),
    ('URGENCES GAP (C)', 'URGENCES GAP (C)'),
    ('CONSULTATION POST URGENCE ©', 'CONSULTATION POST URGENCE ©'),
    ('VIOLENCES FAITES AUX FEMMES', 'VIOLENCES FAITES AUX FEMMES'),
    ('DEPISTAGE COVID 19 (C)', 'DEPISTAGE COVID 19 (C)'),
    ('MEDECINS CORRESPONDANT SAMU', 'MEDECINS CORRESPONDANT SAMU'),
    ('UMSP RV', 'UMSP RV'),
    ('PASS Mobile', 'PASS Mobile'),
    ('USMP', 'USMP'),
    ('UHTCD - S (HC)', 'UHTCD - S (HC)'),
    ('UHTCD COVID - S (HC)', 'UHTCD COVID - S (HC)'),
    ('S.M.U. - S (C)', 'S.M.U. - S (C)'),
    ('URGENCES SISTERON (C)', 'URGENCES SISTERON (C)'),
    ('REANIMATION SSPI 2 (HEB)', 'REANIMATION SSPI 2 (HEB)'),
    ('SURV CONTINUE POLY OPTIFLOW (HC)', 'SURV CONTINUE POLY OPTIFLOW (HC)'),
    ('SURVEILLANCE CONTINUE 2 SSPI (HEB)', 'SURVEILLANCE CONTINUE 2 SSPI (HEB)'),
    ('MAISON MEDICALE DE GARDE (C)', 'MAISON MEDICALE DE GARDE (C)'),
    ('TELEMEDECINE DIALYSE (C)', 'TELEMEDECINE DIALYSE (C)'),
    ('DIALYSE (C) - S', 'DIALYSE (C) - S'),
    ('KINESITHERAPIE - ADRET GERONTOLOGIE', 'KINESITHERAPIE - ADRET GERONTOLOGIE'),
    ('CUISINE EDUCATIVE GERONTOLOGIE', 'CUISINE EDUCATIVE GERONTOLOGIE'),
    ('ERGOTHERAPIE GERONTOLOGIE', 'ERGOTHERAPIE GERONTOLOGIE'),
    ('ORTHOGENIE (C)', 'ORTHOGENIE (C)'),
    ('PSYCHIATRIE SECTEUR (C)', 'PSYCHIATRIE SECTEUR (C)'),
    ('SERVICE DE SANTE AU TRAVAIL', 'SERVICE DE SANTE AU TRAVAIL'),
    ('MISE A DISPO SYND NAT & LOC', 'MISE A DISPO SYND NAT & LOC'),
    ('SERVICE DE SANTE AU TRAVAIL', 'SERVICE DE SANTE AU TRAVAIL'),
    ('I.R.M. 1 PUBLIC', 'I.R.M. 1 PUBLIC'),
    ('OSTEODENSITOMETRIE', 'OSTEODENSITOMETRIE'),
    ('RADIOTHERAPIE (C)', 'RADIOTHERAPIE (C)'),
    ('RADIOTHERAPIE (SIMULATION)', 'RADIOTHERAPIE (SIMULATION)'),
    ('ECHOGRAPHIE - S', 'ECHOGRAPHIE - S'),
    ('LABORATOIRE - ETS EXTERIEURS', 'LABORATOIRE - ETS EXTERIEURS'),
    ('LABORATOIRE TERRITORIAL (C)', 'LABORATOIRE TERRITORIAL (C)'),
    ('LABORATOIRE - GAP', 'LABORATOIRE - GAP'),
    ('LABORATOIRE - CH BRIANCON', 'LABORATOIRE - CH BRIANCON'),
    ('LABORATOIRE  - SISTERON', 'LABORATOIRE  - SISTERON'),
    ('CHIRURGIE ORALE (C)', 'CHIRURGIE ORALE (C)'),
    ('BLOC ORTHO/TRAUMATOLOGIQUE', 'BLOC ORTHO/TRAUMATOLOGIQUE'),
    ('BLOC CHIRURGIE VISCERALE', 'BLOC CHIRURGIE VISCERALE'),
    ('BLOC CHIRURGIE UROLOGIQUE', 'BLOC CHIRURGIE UROLOGIQUE'),
    ('BLOC CHIRURGIE ORALE', 'BLOC CHIRURGIE ORALE'),
    ('BLOC CHIR VISCERALE', 'BLOC CHIR VISCERALE'),
    ('BLOC CHIR UROLOGIQUE', 'BLOC CHIR UROLOGIQUE'),
    ('BLOC ORTHO/TRAUMATOLOGIQUE', 'BLOC ORTHO/TRAUMATOLOGIQUE'),
    ('ALGOLOGIE (C) - S', 'ALGOLOGIE (C) - S'),
    ('TELEMEDECINE ALGOLOGIE (C)', 'TELEMEDECINE ALGOLOGIE (C)'),
    ('C.F.P.S. - PREPA CONCOURS IDE', 'C.F.P.S. - PREPA CONCOURS IDE'),
    ('C.F.P.S. - PREPA CONCOURS AS', 'C.F.P.S. - PREPA CONCOURS AS'),
    ('C.F.P.S. - FORMATION CONTINUE', 'C.F.P.S. - FORMATION CONTINUE'),
    ('HOSPITALISATION A DOMICILE', 'HOSPITALISATION A DOMICILE'),
    ('CEGGID & IST', 'CEGGID & IST'),
    ('CENTRE VACCINATION COVID 19 (C)', 'CENTRE VACCINATION COVID 19 (C)'),
    ('CENTRE VACCINATION COVID 19 - S (C)', 'CENTRE VACCINATION COVID 19 - S (C)'),
    ('CENTRE VACCINATION COVID 19 - CMCL', 'CENTRE VACCINATION COVID 19 - CMCL'),
    ('HOPITAL DE JOUR DE MEDECINE', 'HOPITAL DE JOUR DE MEDECINE'),
    ('HDJ PNEUMO GASTRO', 'HDJ PNEUMO GASTRO'),
    ('CHIRURGIE AMBULATOIRE (HJ)', 'CHIRURGIE AMBULATOIRE (HJ)'),
    ('CHIR AMBU - UROLOGIE', 'CHIR AMBU - UROLOGIE'),
    ('CHIR AMBU - ORTHO-TRAUMATOLOGIE', 'CHIR AMBU - ORTHO-TRAUMATOLOGIE'),
    ('CHIR AMBU - VISCERALE', 'CHIR AMBU - VISCERALE'),
    ('CHIR AMBU - OPHTALMOLOGIE', 'CHIR AMBU - OPHTALMOLOGIE'),
    ('CHIR AMBU ORL & ORALE', 'CHIR AMBU ORL & ORALE'),
    ('CHIR AMBU - ALGOLOGIE', 'CHIR AMBU - ALGOLOGIE'),
    ('CHIR AMBU - GYNECOLOGIE', 'CHIR AMBU - GYNECOLOGIE'),
    ('CHIR AMBU - GASTRO-ENTEROLOGIE', 'CHIR AMBU - GASTRO-ENTEROLOGIE'),
    ('CHIR AMBU - CARDIOLOGIE', 'CHIR AMBU - CARDIOLOGIE'),
    ('CHIR AMBU - PNEUMOLOGIE', 'CHIR AMBU - PNEUMOLOGIE'),
    ('I.R.M. 2 PRIVE', 'I.R.M. 2 PRIVE'),
    ('MEDECINS DU MONDE PRESTATIONS', 'MEDECINS DU MONDE PRESTATIONS'),
    ('GIE IRM', 'GIE IRM'),
    ('POLYCLINIQUE ALPES DU SUD PRESTATIONS', 'POLYCLINIQUE ALPES DU SUD PRESTATIONS'),
    ('BLANCHISSERIE GCS (PLATEFORME HOSP 05)', 'BLANCHISSERIE GCS (PLATEFORME HOSP 05)'),
    ('SERVICE DIETETIQUE', 'SERVICE DIETETIQUE'),
    ('DISTRIBUTION/COLLECTES CHICAS INTERNE', 'DISTRIBUTION/COLLECTES CHICAS INTERNE'),
    ('DISTRIB/COLLECTES CHICAS EXTERNE', 'DISTRIB/COLLECTES CHICAS EXTERNE'),
    ('GARAGE', 'GARAGE'),
    ('SERVICE BIOMEDICAL - DM STOCK DE CRISE', 'SERVICE BIOMEDICAL - DM STOCK DE CRISE'),
    ('LINGERIE BLANCHISSERIE - GAP', 'LINGERIE BLANCHISSERIE - GAP'),
    ('DISTRIBUTION/COLLECTES GCS (PLATEFORME HOSP 05)', 'DISTRIBUTION/COLLECTES GCS (PLATEFORME HOSP 05)'),
    ('DEMENAGEMENT MANUTENTION', 'DEMENAGEMENT MANUTENTION'),
    ('DENEIGEMENT', 'DENEIGEMENT'),
    ('SMR GERIATRIQUE', 'SMR GERIATRIQUE'),
    ('SMR - UCC', 'SMR - UCC'),
    ('SMR SPECIALISE - S (HJ)', 'SMR SPECIALISE - S (HJ)'),
    ('SMR INDIFFERENCIE - S (HC)', 'SMR INDIFFERENCIE - S (HC)'),
    ('CESU Embrun', 'CESU Embrun'),
    ('MAGASIN PHARMACIE - PRÊT', 'MAGASIN PHARMACIE - PRÊT'),
    ('MAGASIN LABORATOIRE - B Effet au 11/12/2023', 'MAGASIN LABORATOIRE - B Effet au 11/12/2023'),
    ('BONI MAGASIN - S', 'BONI MAGASIN - S'),
    ('BONI PHARMACIE - S', 'BONI PHARMACIE - S'),
    ('BONI MAGASIN ECONOMAT - S', 'BONI MAGASIN ECONOMAT - S'),
    ('BONI MAGASIN LABORATOIRE - S', 'BONI MAGASIN LABORATOIRE - S'),
    ('BONI MAGASIN GENERAL', 'BONI MAGASIN GENERAL'),
    ('BONI MAG.PHARMACIE', 'BONI MAG.PHARMACIE'),
    ('BONI MAG LABORATOIRE', 'BONI MAG LABORATOIRE'),
    ('BONI MAG.ALIMENTATION', 'BONI MAG.ALIMENTATION'),
]

DOCUMENT_TYPES = {
    'quote': 'Devis',
    'purchase_order': 'Bon de commande',
    'reception': 'Bon de réception',
}


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password_hash = db.Column(db.String(256), nullable=False)
    role = db.Column(db.String(32), nullable=False)
    verified = db.Column(db.Boolean, default=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    cases_created = db.relationship('Case', backref='engineer', foreign_keys='Case.engineer_id')
    documents_uploaded = db.relationship('Document', backref='uploader', foreign_keys='Document.uploaded_by_id')
    documents_signed = db.relationship('Document', backref='signer', foreign_keys='Document.signer_id')
    signature = db.relationship('Signature', back_populates='user', uselist=False)

    def set_password(self, password: str):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password: str) -> bool:
        return check_password_hash(self.password_hash, password)

    def can_create_case(self) -> bool:
        return self.role == 'engineer'

    def can_upload(self, case) -> bool:
        if self.role == 'supplier':
            return self.email.lower() == (case.supplier_email or '').lower()
        if self.role == 'buyer':
            return case.has_signed_quote()
        return False

    def can_sign(self, document) -> bool:
        return self.role == 'engineer' and self.id == document.case.engineer_id


class Case(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(150), nullable=False)
    description = db.Column(db.Text, nullable=True)
    type = db.Column(db.String(80), nullable=False)
    object_contract = db.Column(db.String(200), nullable=True)
    start_date = db.Column(db.String(20), nullable=True)
    duration = db.Column(db.String(100), nullable=True)
    market = db.Column(db.String(120), nullable=True)
    budget = db.Column(db.String(120), nullable=True)
    uf_number = db.Column(db.String(120), nullable=True)
    supplier_email = db.Column(db.String(120), nullable=False)
    provider_designation = db.Column(db.String(200), nullable=True)
    buyer_email = db.Column('supplier_contact', db.String(120), nullable=True)
    billing_terms = db.Column(db.String(120), nullable=True)
    invoice_on_delivery = db.Column(db.Boolean, default=False)
    invoice_on_order = db.Column(db.Boolean, default=False)
    account_number = db.Column(db.String(120), nullable=True)
    project_code = db.Column(db.String(120), nullable=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    engineer_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

    documents = db.relationship('Document', backref='case', lazy=True)

    def get_document(self, doc_type):
        return Document.query.filter_by(case_id=self.id, type=doc_type).order_by(Document.uploaded_at.desc()).first()

    def has_signed_quote(self):
        quote = self.get_document('quote')
        return bool(quote and quote.is_signed)

    def has_purchase_order(self):
        return bool(self.get_document('purchase_order'))

    def has_signed_reception(self):
        receipt = self.get_document('reception')
        return bool(receipt and receipt.is_signed)


class Document(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    case_id = db.Column(db.Integer, db.ForeignKey('case.id'), nullable=False)
    type = db.Column(db.String(32), nullable=False)
    filename = db.Column(db.String(250), nullable=False)
    uploaded_at = db.Column(db.DateTime, default=datetime.utcnow)
    uploaded_by_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    is_signed = db.Column(db.Boolean, default=False)
    signed_at = db.Column(db.DateTime, nullable=True)
    signer_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=True)

    def display_type(self):
        return DOCUMENT_TYPES.get(self.type, self.type)


class VerificationToken(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    token = db.Column(db.String(120), unique=True, nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    user = db.relationship('User', backref=db.backref('verification_token', uselist=False))


class Signature(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), unique=True, nullable=False)
    first_name = db.Column(db.String(80), nullable=False)
    last_name = db.Column(db.String(80), nullable=False)
    function_title = db.Column(db.String(120), nullable=False)
    stamp_filename = db.Column(db.String(250), nullable=True)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow)
    user = db.relationship('User', back_populates='signature')


class LoginForm(FlaskForm):
    username = StringField('Nom d’utilisateur', validators=[DataRequired(), Length(min=3, max=80)])
    password = PasswordField('Mot de passe', validators=[DataRequired()])
    submit = SubmitField('Se connecter')


class RegisterForm(FlaskForm):
    username = StringField('Nom d’utilisateur', validators=[DataRequired(), Length(min=3, max=80)])
    email = StringField('Adresse e-mail', validators=[DataRequired(), Email()])
    role = SelectField(
        'Rôle',
        choices=[
            ('engineer', 'Ingénieur'),
            ('supplier', 'Fournisseur'),
            ('buyer', 'Acheteur'),
        ],
        validators=[DataRequired()],
    )
    password = PasswordField('Mot de passe', validators=[DataRequired(), Length(min=6)])
    confirm = PasswordField('Confirmer le mot de passe', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Créer un compte')


class CaseForm(FlaskForm):
    title = StringField('Titre de l’affaire', validators=[DataRequired()])
    description = TextAreaField('Description')
    type = SelectField('Type de prestation', choices=CASE_TYPES, validators=[DataRequired()])
    object_contract = StringField('Objet du contrat')
    start_date = StringField('Date d’effet')
    duration = StringField('Durée')
    market = StringField('Marché')
    budget = StringField('Budget investissement H')
    account_number = SelectField('N° de compte', choices=ACCOUNT_NUMBER_CHOICES)
    project_code = SelectField('Code projet', choices=PROJECT_CODE_CHOICES)
    uf_number = SelectField('N° UF', choices=UF_CHOICES)
    supplier_email = StringField('Courriel du fournisseur', validators=[DataRequired(), Email()])
    buyer_email = StringField('Courriel de l’acheteur', validators=[DataRequired(), Email()])
    provider_designation = StringField('Désignation commande')
    billing_terms = SelectField('Modalité de facturation', choices=[('mensuel', 'mensuel'), ('trimestriel', 'trimestriel'), ('autre', 'Autre')])
    invoice_on_delivery = SelectField('Facturation à réception de PV', choices=[('oui', 'Oui'), ('non', 'Non')])
    invoice_on_order = SelectField('Facturation à réception de commande', choices=[('oui', 'Oui'), ('non', 'Non')])
    submit = SubmitField('Créer l’affaire')


class UploadForm(FlaskForm):
    document = StringField('Document')
    submit = SubmitField('Téléverser le fichier PDF')


class SignatureForm(FlaskForm):
    first_name = StringField('Prénom', validators=[DataRequired(), Length(max=80)])
    last_name = StringField('Nom', validators=[DataRequired(), Length(max=80)])
    function_title = StringField('Fonction', validators=[DataRequired(), Length(max=120)])
    submit = SubmitField('Enregistrer la signature')


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


def allowed_file(filename: str) -> bool:
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


def allowed_image(filename: str) -> bool:
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_IMAGE_EXTENSIONS


def create_signature_overlay(page_width: float, page_height: float, page_rotation: int, signature, stamp_path: Path | None) -> Path:
    overlay_path = UPLOAD_FOLDER / f'overlay_{uuid.uuid4().hex}.pdf'

    c = canvas.Canvas(str(overlay_path), pagesize=(page_width, page_height))
    margin = 40
    image_width = 0
    image_height = 0
    text_align = 'right'

    if stamp_path and stamp_path.exists():
        try:
            image = ImageReader(str(stamp_path))
            iw, ih = image.getSize()
            max_w = 160
            max_h = 160
            ratio = min(max_w / iw, max_h / ih, 1)
            image_width = iw * ratio
            image_height = ih * ratio
        except Exception:
            image_width = 0
            image_height = 0

    rotation = page_rotation % 360
    if rotation in (0, 90):
        image_x = page_width - image_width - margin
        text_x = page_width - margin
        text_align = 'right'
    else:
        image_x = margin
        text_x = margin
        text_align = 'left'

    if rotation in (0, 270):
        image_y = margin
        text_y = image_y + image_height + 12
    else:
        image_y = page_height - image_height - margin
        text_y = image_y - 12

    if stamp_path and stamp_path.exists() and image_width and image_height:
        try:
            image = ImageReader(str(stamp_path))
            c.drawImage(image, image_x, image_y, width=image_width, height=image_height, mask='auto')
        except Exception:
            pass

    c.setFont('Helvetica-Bold', 12)
    if text_align == 'right':
        c.drawRightString(text_x, text_y, f'{signature.first_name} {signature.last_name}')
        c.setFont('Helvetica', 11)
        c.drawRightString(text_x, text_y - 16, signature.function_title)
        c.drawRightString(text_x, text_y - 32, f'Date : {datetime.utcnow().strftime("%d/%m/%Y %H:%M")}')
    else:
        c.drawString(text_x, text_y, f'{signature.first_name} {signature.last_name}')
        c.setFont('Helvetica', 11)
        c.drawString(text_x, text_y - 16, signature.function_title)
        c.drawString(text_x, text_y - 32, f'Date : {datetime.utcnow().strftime("%d/%m/%Y %H:%M")}')

    c.save()
    return overlay_path


def merge_signature_to_pdf(original_pdf_path: Path, signature, stamp_path: Path | None, output_pdf_path: Path) -> None:
    reader = PdfReader(str(original_pdf_path))
    writer = PdfWriter()

    for page in reader.pages:
        width = float(page.mediabox.width)
        height = float(page.mediabox.height)
        rotation = int(page.get('/Rotate', 0) or 0) % 360
        overlay_path = create_signature_overlay(width, height, rotation, signature, stamp_path)
        overlay = PdfReader(str(overlay_path))
        overlay_page = overlay.pages[0]
        page.merge_page(overlay_page)
        writer.add_page(page)
        try:
            overlay_path.unlink()
        except OSError:
            pass

    with open(output_pdf_path, 'wb') as output_file:
        writer.write(output_file)


def ensure_directories():
    UPLOAD_FOLDER.mkdir(parents=True, exist_ok=True)
    DATABASE_PATH.parent.mkdir(parents=True, exist_ok=True)


def seed_users():
    created = False

    if not User.query.filter_by(username='engineer').first():
        engineer = User(username='engineer', email='engineer@example.com', role='engineer', verified=True)
        engineer.set_password('password')
        db.session.add(engineer)
        created = True

    if not User.query.filter_by(username='buyer').first():
        buyer = User(username='buyer', email='buyer@example.com', role='buyer', verified=True)
        buyer.set_password('password')
        db.session.add(buyer)
        created = True

    if not User.query.filter_by(username='supplier').first():
        supplier = User(username='supplier', email='supplier@example.com', role='supplier', verified=True)
        supplier.set_password('password')
        db.session.add(supplier)
        created = True

    if created:
        db.session.commit()
        app.logger.info('Created demo users: engineer/password, buyer/password and supplier/password')


def send_email(recipient: str, subject: str, body: str):
    if not app.config['MAIL_SERVER']:
        app.logger.info('Email stub to %s: %s', recipient, subject)
        app.logger.info(body)
        return

    message = EmailMessage()
    message['Subject'] = subject
    message['From'] = app.config['MAIL_DEFAULT_SENDER']
    message['To'] = recipient
    message.set_content(body)

    try:
        if app.config['MAIL_USE_SSL']:
            smtp = smtplib.SMTP_SSL(app.config['MAIL_SERVER'], app.config['MAIL_PORT'], timeout=10)
        else:
            smtp = smtplib.SMTP(app.config['MAIL_SERVER'], app.config['MAIL_PORT'], timeout=10)
        smtp.ehlo()
        if app.config['MAIL_USE_TLS'] and not app.config['MAIL_USE_SSL']:
            smtp.starttls()
            smtp.ehlo()
        if app.config['MAIL_USERNAME'] and app.config['MAIL_PASSWORD']:
            smtp.login(app.config['MAIL_USERNAME'], app.config['MAIL_PASSWORD'])
        smtp.send_message(message)
        smtp.quit()
    except Exception as exc:
        app.logger.warning('Email send failed: %s', exc)


db_initialized = False


def user_required(role):
    def decorator(f):
        @wraps(f)
        def wrapped(*args, **kwargs):
            if not current_user.is_authenticated or current_user.role != role:
                flash('Accès refusé.', 'warning')
                return redirect(url_for('dashboard'))
            return f(*args, **kwargs)

        return wrapped

    return decorator


def ensure_database_schema():
    engine = db.engine
    if engine.url.drivername == 'sqlite':
        with engine.connect() as conn:
            result = conn.execute(text("PRAGMA table_info('case')"))
            existing_columns = {row['name'] for row in result.mappings()}
            if 'project_code' not in existing_columns:
                conn.execute(text('ALTER TABLE "case" ADD COLUMN project_code VARCHAR(120)'))


def initialize_database():
    global db_initialized
    if db_initialized:
        return

    ensure_directories()
    db.create_all()
    ensure_database_schema()
    seed_users()
    db_initialized = True


@app.before_request
def before_request():
    initialize_database()


@app.route('/')
@login_required
def dashboard():
    if current_user.role == 'engineer':
        cases = Case.query.filter_by(engineer_id=current_user.id).order_by(Case.created_at.desc()).all()
    elif current_user.role == 'supplier':
        cases = Case.query.filter(Case.supplier_email.ilike(f'%{current_user.email}%')).order_by(Case.created_at.desc()).all()
    else:
        cases = Case.query.order_by(Case.created_at.desc()).all()
    return render_template('dashboard.html', cases=cases)


@app.route('/signature', methods=['GET', 'POST'])
@login_required
def signature_settings():
    if current_user.role != 'engineer':
        flash('Accès refusé.', 'warning')
        return redirect(url_for('dashboard'))

    signature = current_user.signature or Signature(user_id=current_user.id)
    form = SignatureForm(obj=signature)

    if request.method == 'POST' and 'delete_signature' in request.form:
        if signature.id:
            if signature.stamp_filename:
                stamp_path = UPLOAD_FOLDER / signature.stamp_filename
                try:
                    if stamp_path.exists():
                        stamp_path.unlink()
                except OSError:
                    pass
            db.session.delete(signature)
            db.session.commit()
            flash('Signature supprimée.', 'success')
        else:
            flash('Aucune signature à supprimer.', 'warning')
        return redirect(url_for('dashboard'))

    if form.validate_on_submit():
        signature.first_name = form.first_name.data
        signature.last_name = form.last_name.data
        signature.function_title = form.function_title.data
        signature.updated_at = datetime.utcnow()

        file = request.files.get('stamp_image')
        if file and file.filename:
            if not allowed_image(file.filename):
                flash('Seuls les fichiers PNG, JPG et JPEG sont autorisés pour le tampon.', 'danger')
                return redirect(request.url)
            filename = secure_filename(file.filename)
            unique_name = f'signature_{current_user.id}_{uuid.uuid4().hex}_{filename}'
            file_path = UPLOAD_FOLDER / unique_name
            file.save(file_path)
            signature.stamp_filename = unique_name

        db.session.add(signature)
        db.session.commit()
        flash('Signature enregistrée.', 'success')
        return redirect(url_for('dashboard'))

    return render_template('signature.html', form=form, signature=signature)


@app.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('dashboard'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and user.check_password(form.password.data):
            if not user.verified:
                flash('Votre compte n’est pas vérifié. Vérifiez votre email.', 'warning')
            else:
                login_user(user)
                return redirect(url_for('dashboard'))
        else:
            flash('Nom d’utilisateur ou mot de passe incorrect.', 'danger')

    return render_template('login.html', form=form)


@app.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('login'))


@app.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('dashboard'))

    form = RegisterForm()
    if form.validate_on_submit():
        existing_user = User.query.filter((User.username == form.username.data) | (User.email == form.email.data)).first()
        if existing_user:
            flash('Le nom d’utilisateur ou l’adresse e-mail existe déjà.', 'warning')
        else:
            user = User(
                username=form.username.data,
                email=form.email.data,
                role=form.role.data,
                verified=False,
            )
            user.set_password(form.password.data)
            db.session.add(user)
            db.session.commit()
            token = VerificationToken(user_id=user.id, token=str(uuid.uuid4()))
            db.session.add(token)
            db.session.commit()
            verify_url = url_for('verify_email', token=token.token, _external=True)
            send_email(
                user.email,
                'Vérifiez votre adresse e-mail',
                f'Bonjour {user.username},\n\nCliquez sur le lien pour vérifier votre compte:\n{verify_url}',
            )
            flash('Inscription réussie. Vérifiez votre email pour activer votre compte.', 'success')
            return redirect(url_for('login'))

    return render_template('register.html', form=form)


@app.route('/verify/<token>')
def verify_email(token):
    verification = VerificationToken.query.filter_by(token=token).first()
    if verification and verification.user:
        verification.user.verified = True
        db.session.delete(verification)
        db.session.commit()
        flash('Compte vérifié, vous pouvez vous connecter.', 'success')
    else:
        flash('Lien de vérification invalide ou expiré.', 'danger')
    return redirect(url_for('login'))


@app.route('/cases/new', methods=['GET', 'POST'])
@login_required
@user_required('engineer')
def create_case():
    form = CaseForm()
    if form.validate_on_submit():
        case = Case(
            title=form.title.data,
            description=form.description.data,
            type=form.type.data,
            object_contract=form.object_contract.data,
            start_date=form.start_date.data,
            duration=form.duration.data,
            market=form.market.data,
            budget=form.budget.data,
            account_number=form.account_number.data,
            project_code=form.project_code.data,
            uf_number=form.uf_number.data,
            supplier_email=form.supplier_email.data,
            buyer_email=form.buyer_email.data,
            provider_designation=form.provider_designation.data,
            billing_terms=form.billing_terms.data,
            invoice_on_delivery=form.invoice_on_delivery.data == 'oui',
            invoice_on_order=form.invoice_on_order.data == 'oui',
            engineer_id=current_user.id,
        )
        db.session.add(case)
        db.session.commit()

        supplier = User.query.filter_by(email=case.supplier_email).first()
        if supplier and supplier.verified:
            send_email(
                supplier.email,
                'Un devis a été demandé pour une nouvelle affaire',
                f'Une nouvelle affaire a été créée et vous êtes invité à déposer un devis pour {case.title}.',
            )

        if case.buyer_email:
            send_email(
                case.buyer_email,
                'Nouvelle affaire créée',
                f'Une nouvelle affaire a été créée pour {case.title}.',
            )

        flash('Affaire créée. Le fournisseur et l’acheteur ont été notifiés.', 'success')
        return redirect(url_for('dashboard'))

    return render_template('case_form.html', form=form)


@app.route('/cases/<int:case_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_case(case_id):
    case = Case.query.get_or_404(case_id)
    is_engineer = current_user.role == 'engineer' and current_user.id == case.engineer_id
    is_buyer = current_user.role == 'buyer' and case.buyer_email and current_user.email.lower() == case.buyer_email.lower()
    if not (is_engineer or is_buyer):
        flash('Vous ne pouvez pas modifier cette affaire.', 'warning')
        return redirect(url_for('case_detail', case_id=case.id))

    form = CaseForm(obj=case)
    buyer_edit = is_buyer
    if buyer_edit:
        form.title.render_kw = {'readonly': True, 'disabled': True}

    if form.validate_on_submit():
        if not buyer_edit:
            case.title = form.title.data
        case.description = form.description.data
        case.type = form.type.data
        case.object_contract = form.object_contract.data
        case.start_date = form.start_date.data
        case.duration = form.duration.data
        case.market = form.market.data
        case.budget = form.budget.data
        case.account_number = form.account_number.data or None
        case.project_code = form.project_code.data or None
        case.uf_number = form.uf_number.data or None
        case.supplier_email = form.supplier_email.data
        case.buyer_email = form.buyer_email.data
        case.provider_designation = form.provider_designation.data
        case.billing_terms = form.billing_terms.data
        case.invoice_on_delivery = form.invoice_on_delivery.data == 'oui'
        case.invoice_on_order = form.invoice_on_order.data == 'oui'
        db.session.commit()
        flash('Affaire mise à jour.', 'success')
        return redirect(url_for('case_detail', case_id=case.id))

    return render_template('case_form.html', form=form, edit=True, buyer_edit=buyer_edit)


@app.route('/cases/<int:case_id>')
@login_required
def case_detail(case_id):
    case = Case.query.get_or_404(case_id)
    quote = case.get_document('quote')
    purchase_order = case.get_document('purchase_order')
    reception = case.get_document('reception')
    return render_template(
        'case_detail.html',
        case=case,
        quote=quote,
        purchase_order=purchase_order,
        reception=reception,
        doc_types=DOCUMENT_TYPES,
    )


@app.route('/cases/<int:case_id>/upload/<string:doc_type>', methods=['GET', 'POST'])
@login_required
def upload_document(case_id, doc_type):
    if doc_type not in DOCUMENT_TYPES:
        flash('Type de document invalide.', 'danger')
        return redirect(url_for('case_detail', case_id=case_id))

    case = Case.query.get_or_404(case_id)
    if not current_user.can_upload(case):
        flash('Vous ne pouvez pas téléverser ce document.', 'warning')
        return redirect(url_for('case_detail', case_id=case_id))

    if request.method == 'POST':
        file = request.files.get('file')
        if not file or file.filename == '':
            flash('Aucun fichier sélectionné.', 'warning')
            return redirect(request.url)
        if not allowed_file(file.filename):
            flash('Seuls les fichiers PDF sont autorisés.', 'danger')
            return redirect(request.url)

        filename = secure_filename(file.filename)
        unique_name = f'{case.id}_{doc_type}_{uuid.uuid4().hex}_{filename}'
        file_path = UPLOAD_FOLDER / unique_name
        file.save(file_path)

        document = Document(
            case_id=case.id,
            type=doc_type,
            filename=unique_name,
            uploaded_by_id=current_user.id,
        )
        db.session.add(document)
        db.session.commit()

        subject = f'{DOCUMENT_TYPES[doc_type]} déposé pour l’affaire {case.title}'
        if current_user.role == 'supplier':
            recipients = [case.engineer.email]
            body = f'Le devis a été déposé par le fournisseur pour l’affaire {case.title}. Connectez-vous pour signer.'
        elif current_user.role == 'buyer':
            recipients = [case.engineer.email, case.supplier_email]
            body = f'Le {DOCUMENT_TYPES[doc_type].lower()} a été déposé pour l’affaire {case.title}. Connectez-vous pour le consulter.'
        else:
            recipients = [case.engineer.email]
            body = f'Le {DOCUMENT_TYPES[doc_type].lower()} a été déposé pour l’affaire {case.title}.'

        for recipient in set(recipients):
            send_email(recipient, subject, body)
        flash('Document téléchargé.', 'success')
        return redirect(url_for('case_detail', case_id=case.id))

    return render_template('upload.html', case=case, doc_type=doc_type, doc_label=DOCUMENT_TYPES[doc_type])


@app.route('/documents/<path:filename>')
@login_required
def document_file(filename):
    return send_from_directory(UPLOAD_FOLDER, filename, as_attachment=True)


@app.route('/documents/<int:document_id>/view')
@login_required
def view_document(document_id):
    document = Document.query.get_or_404(document_id)
    return send_from_directory(UPLOAD_FOLDER, document.filename, as_attachment=False)


@app.route('/documents/<int:document_id>/sign')
@login_required
def sign_document(document_id):
    document = Document.query.get_or_404(document_id)
    case = document.case
    if current_user.role != 'engineer' or current_user.id != case.engineer_id:
        flash('Vous ne pouvez pas signer ce document.', 'warning')
        return redirect(url_for('case_detail', case_id=case.id))

    if document.is_signed:
        flash('Ce document est déjà signé.', 'warning')
        return redirect(url_for('case_detail', case_id=case.id))

    if not current_user.signature:
        flash('Définissez d’abord votre signature avant de signer.', 'warning')
        return redirect(url_for('signature_settings'))

    original_path = UPLOAD_FOLDER / document.filename
    if not original_path.exists():
        flash('Le fichier PDF est introuvable.', 'danger')
        return redirect(url_for('case_detail', case_id=case.id))

    signed_filename = f'{case.id}_{document.type}_signed_{uuid.uuid4().hex}.pdf'
    signed_path = UPLOAD_FOLDER / signed_filename

    try:
        merge_signature_to_pdf(
            original_path,
            current_user.signature,
            UPLOAD_FOLDER / current_user.signature.stamp_filename if current_user.signature.stamp_filename else None,
            signed_path,
        )
    except Exception as exc:
        flash('Impossible de signer le PDF : %s' % exc, 'danger')
        return redirect(url_for('case_detail', case_id=case.id))

    document.filename = signed_filename
    document.is_signed = True
    document.signed_at = datetime.utcnow()
    document.signer_id = current_user.id
    db.session.commit()

    if document.type == 'quote':
        subject = f'Devis signé pour l’affaire {case.title}'
        body = 'Le devis a été signé par l’ingénieur.'
        recipients = [case.supplier_email]
        if case.buyer_email:
            recipients.append(case.buyer_email)
    elif document.type == 'purchase_order':
        subject = f'Bon de commande signé pour l’affaire {case.title}'
        body = 'Le bon de commande a été signé pour l’affaire.'
        recipients = [case.supplier_email]
        if case.buyer_email:
            recipients.append(case.buyer_email)
    else:
        subject = f'Bon de réception signé pour l’affaire {case.title}'
        body = 'Le bon de réception a été signé par l’ingénieur.'
        recipients = [case.supplier_email]

    for recipient in set(recipients):
        send_email(recipient, subject, body)

    flash('Document signé.', 'success')
    return redirect(url_for('case_detail', case_id=case.id))


@app.route('/documents/<int:document_id>/delete', methods=['POST'])
@login_required
def delete_document(document_id):
    document = Document.query.get_or_404(document_id)
    case = document.case

    if document.is_signed:
        if not (
            current_user.role == 'engineer'
            and current_user.id == case.engineer_id
            and document.type in ('quote', 'purchase_order')
        ) and not (
            current_user.role == 'buyer'
            and document.type in ('purchase_order', 'reception')
        ):
            flash('Impossible de supprimer un document déjà signé.', 'warning')
            return redirect(url_for('case_detail', case_id=case.id))

    allowed_to_delete = (
        current_user.id == document.uploaded_by_id
        or (current_user.role == 'engineer' and current_user.id == case.engineer_id)
        or (current_user.role == 'buyer' and document.type in ('purchase_order', 'reception'))
    )
    if not allowed_to_delete:
        flash('Vous ne pouvez pas supprimer ce document.', 'warning')
        return redirect(url_for('case_detail', case_id=case.id))

    file_path = UPLOAD_FOLDER / document.filename
    try:
        if file_path.exists():
            file_path.unlink()
    except OSError:
        pass

    db.session.delete(document)
    db.session.commit()
    flash('Document supprimé.', 'success')
    return redirect(url_for('case_detail', case_id=case.id))


if __name__ == '__main__':
    ensure_directories()
    db.create_all()
    app.run(host='0.0.0.0', port=8000, debug=True)
